console.log(Boolean(10));
console.log(Boolean(-10));
console.log(Boolean(0));
console.log(Boolean(Infinity));
console.log(Boolean(NaN));
console.log(Boolean(""));
console.log(Boolean(" "));
console.log(Boolean(null));
console.log(Boolean(undefined));
console.log(Boolean("vedant"));
console.log(Boolean([]));
console.log(Boolean(-0));
console.log(Boolean(!NaN));
